// websites/apex-auto-detail/src/components/Footer.vue
<script setup>
import { useRouter } from 'vue-router'

const router = useRouter()
const currentYear = new Date().getFullYear()

const services = [
  { label: 'Exterior Detailing', path: '/services' },
  { label: 'Interior Detailing', path: '/services' },
  { label: 'Ceramic Coating', path: '/services' },
  { label: 'Paint Correction', path: '/services' },
  { label: 'Packages', path: '/packages' }
]

const company = [
  { label: 'About Us', path: '/about' },
  { label: 'Gallery', path: '/gallery' },
  { label: 'Booking', path: '/booking' },
  { label: 'Contact', path: '/contact' },
  { label: 'Login', path: '/login' }
]
</script>

<template>
  <footer class="footer">
    <div class="footer-main container">
      <div class="footer-brand">
        <router-link to="/" class="footer-logo">
          <svg class="footer-logo-icon" viewBox="0 0 50 40" fill="none">
            <polygon points="25,2 48,38 2,38" stroke="#0066ff" stroke-width="2.5" fill="none" stroke-linejoin="round"/>
            <line x1="10" y1="26" x2="40" y2="26" stroke="#0066ff" stroke-width="1.5"/>
            <line x1="16" y1="32" x2="34" y2="32" stroke="#0066ff" stroke-width="1"/>
          </svg>
          <div class="footer-logo-text">
            <span class="footer-logo-apex">APEX</span>
            <span class="footer-logo-detail">AUTO DETAIL</span>
          </div>
        </router-link>
        <p class="footer-desc">
          Premium mobile and shop-based car detailing. We treat every vehicle like a supercar, delivering perfection in every detail.
        </p>
        <div class="footer-social">
          <a href="#" class="social-link" aria-label="Instagram">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="5"/><circle cx="17.5" cy="6.5" r="1.5" fill="currentColor" stroke="none"/></svg>
          </a>
          <a href="#" class="social-link" aria-label="TikTok">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M19.59 6.69a4.83 4.83 0 01-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 01-2.88 2.5 2.89 2.89 0 01-2.89-2.89 2.89 2.89 0 012.89-2.89c.28 0 .54.04.79.1v-3.52a6.37 6.37 0 00-.79-.05A6.34 6.34 0 003.15 15.2a6.34 6.34 0 006.34 6.34 6.34 6.34 0 006.34-6.34V9.27a8.16 8.16 0 003.76.92V6.69z"/></svg>
          </a>
          <a href="#" class="social-link" aria-label="Facebook">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3V2z"/></svg>
          </a>
          <a href="#" class="social-link" aria-label="YouTube">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M22.54 6.42a2.78 2.78 0 00-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 00-1.94 2A29 29 0 001 11.75a29 29 0 00.46 5.33A2.78 2.78 0 003.4 19.1c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 001.94-2 29 29 0 00.46-5.25 29 29 0 00-.46-5.43z"/><polygon points="9.75,15.02 15.5,11.75 9.75,8.48" fill="#0a0a0a"/></svg>
          </a>
        </div>
      </div>

      <div class="footer-col">
        <h4>Services</h4>
        <ul>
          <li v-for="item in services" :key="item.label">
            <router-link :to="item.path">{{ item.label }}</router-link>
          </li>
        </ul>
      </div>

      <div class="footer-col">
        <h4>Company</h4>
        <ul>
          <li v-for="item in company" :key="item.label">
            <router-link :to="item.path">{{ item.label }}</router-link>
          </li>
        </ul>
      </div>

      <div class="footer-col">
        <h4>Hours & Contact</h4>
        <ul class="footer-info">
          <li>
            <span class="info-label">Mon - Fri</span>
            <span>8:00 AM - 6:00 PM</span>
          </li>
          <li>
            <span class="info-label">Saturday</span>
            <span>9:00 AM - 5:00 PM</span>
          </li>
          <li>
            <span class="info-label">Sunday</span>
            <span>By Appointment</span>
          </li>
          <li class="footer-phone">
            <a href="tel:+15551234567">(555) 123-4567</a>
          </li>
          <li>
            <a href="mailto:info@apexautodetail.com">info@apexautodetail.com</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="footer-bottom">
      <div class="container footer-bottom-inner">
        <p>&copy; {{ currentYear }} Apex Auto Detail. All rights reserved.</p>
        <div class="footer-bottom-links">
          <a href="#">Privacy Policy</a>
          <a href="#">Terms of Service</a>
        </div>
      </div>
    </div>
  </footer>
</template>

<style scoped>
.footer {
  background: var(--secondary);
  border-top: 1px solid var(--border);
  margin-top: auto;
}

.footer-main {
  display: grid;
  grid-template-columns: 1.5fr 1fr 1fr 1.2fr;
  gap: 48px;
  padding: 80px 24px 60px;
}

.footer-logo {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 20px;
}

.footer-logo-icon {
  width: 38px;
  height: 30px;
}

.footer-logo-text {
  display: flex;
  flex-direction: column;
  line-height: 1;
}

.footer-logo-apex {
  font-family: var(--font-heading);
  font-weight: 700;
  font-size: 1.2rem;
  color: var(--white);
  letter-spacing: 4px;
}

.footer-logo-detail {
  font-family: var(--font-body);
  font-weight: 300;
  font-size: 0.6rem;
  color: var(--primary);
  letter-spacing: 3px;
}

.footer-desc {
  color: var(--text-muted);
  font-size: 0.9rem;
  line-height: 1.7;
  margin-bottom: 24px;
}

.footer-social {
  display: flex;
  gap: 12px;
}

.social-link {
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--carbon);
  border-radius: 50%;
  color: var(--silver);
  transition: var(--transition);
}

.social-link svg {
  width: 18px;
  height: 18px;
}

.social-link:hover {
  background: var(--primary);
  color: var(--white);
  transform: translateY(-2px);
}

.footer-col h4 {
  font-family: var(--font-heading);
  font-size: 1.1rem;
  color: var(--white);
  text-transform: uppercase;
  letter-spacing: 1px;
  margin-bottom: 20px;
}

.footer-col ul li {
  margin-bottom: 10px;
}

.footer-col ul li a {
  color: var(--text-muted);
  font-size: 0.9rem;
  transition: color 0.2s;
}

.footer-col ul li a:hover {
  color: var(--primary);
}

.footer-info li {
  display: flex;
  flex-direction: column;
  gap: 2px;
  color: var(--text-muted);
  font-size: 0.9rem;
}

.info-label {
  color: var(--silver);
  font-weight: 500;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.footer-phone a {
  font-family: var(--font-accent);
  font-size: 1rem;
  color: var(--primary) !important;
  font-weight: 600;
}

.footer-bottom {
  border-top: 1px solid var(--border);
  padding: 20px 0;
}

.footer-bottom-inner {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 0.85rem;
  color: var(--text-muted);
}

.footer-bottom-links {
  display: flex;
  gap: 24px;
}

.footer-bottom-links a {
  color: var(--text-muted);
  transition: color 0.2s;
}

.footer-bottom-links a:hover {
  color: var(--primary);
}

@media (max-width: 768px) {
  .footer-main {
    grid-template-columns: 1fr 1fr;
    gap: 36px;
    padding: 48px 16px 36px;
  }

  .footer-brand {
    grid-column: 1 / -1;
  }
}

@media (max-width: 480px) {
  .footer-main {
    grid-template-columns: 1fr;
    gap: 28px;
  }

  .footer-bottom-inner {
    flex-direction: column;
    gap: 12px;
    text-align: center;
  }
}
</style>

// websites/inkcraft-tattoo/src/components/Footer.jsx
import { Link } from 'react-router-dom'
import './Footer.css'

function Footer() {
  return (
    <footer className="footer">
      <div className="container">
        <div className="footer-grid">
          <div className="footer-brand">
            <Link to="/" className="footer-logo">
              <svg width="36" height="36" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M50 5 L62 42 L56 42 L56 85 L44 85 L44 42 L38 42 Z" fill="var(--burnt-orange)"/>
                <path d="M44 80 L50 92 L56 80" fill="none" stroke="var(--burnt-orange)" strokeWidth="2.5"/>
                <circle cx="50" cy="38" r="3" fill="var(--off-white)"/>
              </svg>
              <div>
                <span className="footer-logo-main">INKCRAFT</span>
                <span className="footer-logo-sub">TATTOO STUDIO</span>
              </div>
            </Link>
            <p className="footer-desc">
              Premium tattoo and piercing studio where body art is elevated to fine art.
              Every piece is a collaboration between artist and canvas.
            </p>
            <div className="footer-social">
              <a href="#" aria-label="Instagram">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="2" y="2" width="20" height="20" rx="5" ry="5"/><circle cx="12" cy="12" r="5"/><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/>
                </svg>
              </a>
              <a href="#" aria-label="Facebook">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>
                </svg>
              </a>
              <a href="#" aria-label="TikTok">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M19.59 6.69a4.83 4.83 0 01-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 01-2.88 2.5 2.89 2.89 0 01-2.89-2.89 2.89 2.89 0 012.89-2.89c.28 0 .54.04.79.1v-3.5a6.37 6.37 0 00-.79-.05A6.34 6.34 0 003.15 15.2a6.34 6.34 0 006.34 6.34 6.34 6.34 0 006.34-6.34V8.78a8.28 8.28 0 004.76 1.5v-3.4a4.85 4.85 0 01-1-.19z"/>
                </svg>
              </a>
              <a href="#" aria-label="Pinterest">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M8 12a4 4 0 1 1 8 0c0 2.22-1.79 4-4 4"/><path d="M10 16l-1 4"/><path d="M12 2a10 10 0 1 0 4 19.17"/>
                </svg>
              </a>
            </div>
          </div>

          <div className="footer-col">
            <h4>Quick Links</h4>
            <Link to="/portfolio">Portfolio</Link>
            <Link to="/artists">Our Artists</Link>
            <Link to="/booking">Book a Session</Link>
            <Link to="/piercing">Piercing</Link>
            <Link to="/aftercare">Aftercare</Link>
            <Link to="/contact">Contact</Link>
          </div>

          <div className="footer-col">
            <h4>Services</h4>
            <span>Custom Tattoos</span>
            <span>Cover-ups</span>
            <span>Touch-ups</span>
            <span>Body Piercing</span>
            <span>Consultations</span>
            <span>Flash Days</span>
          </div>

          <div className="footer-col">
            <h4>Studio Hours</h4>
            <div className="footer-hours">
              <div><span>Monday - Friday</span><span>11:00 AM - 9:00 PM</span></div>
              <div><span>Saturday</span><span>10:00 AM - 10:00 PM</span></div>
              <div><span>Sunday</span><span>12:00 PM - 7:00 PM</span></div>
            </div>
            <div className="footer-address">
              <p>742 Industrial Blvd, Suite 108</p>
              <p>Arts District, Portland OR 97209</p>
              <p>(503) 555-0142</p>
              <p>hello@inkcraftstudio.com</p>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <div className="footer-bottom-inner">
            <p>&copy; 2026 Inkcraft Tattoo Studio. All rights reserved.</p>
            <p className="footer-age-notice">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
              </svg>
              You must be 18 years or older for tattoo and piercing services. Valid ID required.
            </p>
            <div className="footer-legal">
              <a href="#">Privacy Policy</a>
              <a href="#">Terms of Service</a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}

export default Footer
