// websites/pristine-cleaning/src/views/Admin.vue
<template>
  <div class="admin-page">
    <!-- Sidebar -->
    <aside class="admin-sidebar">
      <div class="sidebar-logo">
        <svg viewBox="0 0 40 40" fill="none">
          <path d="M20 2L22 12L32 10L24 18L34 22L24 24L28 34L20 26L12 34L16 24L6 22L16 18L8 10L18 12L20 2Z" fill="#2196F3"/>
          <circle cx="20" cy="20" r="4" fill="#ffffff"/>
        </svg>
        <div>
          <span class="sidebar-brand">PRISTINE</span>
          <span class="sidebar-sub">Admin Panel</span>
        </div>
      </div>

      <nav class="sidebar-nav">
        <a href="#" class="sidebar-link active">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>
          Dashboard
        </a>
        <a href="#" class="sidebar-link">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
          Schedule
        </a>
        <a href="#" class="sidebar-link">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg>
          Clients
        </a>
        <a href="#" class="sidebar-link">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="8.5" cy="7" r="4"/><polyline points="17 11 19 13 23 9"/></svg>
          Team
        </a>
        <a href="#" class="sidebar-link">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>
          Revenue
        </a>
        <a href="#" class="sidebar-link">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M12 1v6m0 6v6m-7-3.5l5.196-3m1.608-.928L17 3.5M1 12h6m6 0h6m-3.5 7l-5.196-3m-1.608-.928L6.5 19"/></svg>
          Settings
        </a>
      </nav>

      <div class="sidebar-footer">
        <router-link to="/" class="sidebar-link">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 21H5a2 2 0 01-2-2V5a2 2 0 012-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg>
          Back to Site
        </router-link>
      </div>
    </aside>

    <!-- Main Content -->
    <main class="admin-main">
      <header class="admin-header">
        <div>
          <h1>Dashboard</h1>
          <p>Welcome back, Maya. Here's your overview for today.</p>
        </div>
        <div class="header-actions">
          <div class="admin-search">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
            <input type="text" placeholder="Search jobs, clients..." />
          </div>
          <button class="btn btn-primary" @click="showQuickSchedule = !showQuickSchedule">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="width:16px;height:16px"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
            New Job
          </button>
        </div>
      </header>

      <!-- KPI Cards -->
      <div class="kpi-grid">
        <div v-for="kpi in kpis" :key="kpi.label" class="kpi-card">
          <div class="kpi-icon" :style="{ background: kpi.bg }" v-html="kpi.icon"></div>
          <div class="kpi-info">
            <span class="kpi-label">{{ kpi.label }}</span>
            <span class="kpi-value">{{ kpi.value }}</span>
            <span class="kpi-trend" :class="kpi.trendType">{{ kpi.trend }}</span>
          </div>
        </div>
      </div>

      <!-- Chart and Quick Schedule -->
      <div class="admin-grid">
        <!-- Revenue Chart -->
        <div class="admin-card chart-card">
          <h3>Monthly Revenue</h3>
          <div class="chart-container">
            <div class="chart-bars">
              <div v-for="bar in chartData" :key="bar.month" class="chart-bar-group">
                <div class="chart-bar" :style="{ height: bar.height + '%' }">
                  <span class="chart-value">${{ bar.value }}</span>
                </div>
                <span class="chart-label">{{ bar.month }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Quick Schedule -->
        <div class="admin-card">
          <h3>Quick Schedule</h3>
          <div v-if="showQuickSchedule" class="quick-form">
            <div class="form-group">
              <label>Client</label>
              <select><option>Sarah Mitchell</option><option>David Chen</option><option>Emily Rodriguez</option></select>
            </div>
            <div class="form-group">
              <label>Service</label>
              <select><option>Regular Cleaning</option><option>Deep Cleaning</option><option>Move In/Out</option></select>
            </div>
            <div class="form-group">
              <label>Date</label>
              <input type="date" />
            </div>
            <button class="btn btn-primary" style="width:100%" @click="showQuickSchedule = false">Schedule Job</button>
          </div>
          <div v-else class="upcoming-jobs">
            <h4>Today's Schedule</h4>
            <div v-for="job in todayJobs" :key="job.time" class="job-item">
              <div class="job-time">{{ job.time }}</div>
              <div class="job-detail">
                <strong>{{ job.client }}</strong>
                <span>{{ job.service }}</span>
              </div>
              <span class="job-status" :class="job.status">{{ job.statusLabel }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Jobs Table -->
      <div class="admin-card">
        <div class="table-header">
          <h3>Recent Jobs</h3>
          <div class="table-actions">
            <select class="table-filter">
              <option>All Status</option>
              <option>Completed</option>
              <option>In Progress</option>
              <option>Scheduled</option>
            </select>
          </div>
        </div>
        <div class="table-wrapper">
          <table class="admin-table">
            <thead>
              <tr>
                <th>Job ID</th>
                <th>Client</th>
                <th>Service</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="job in jobs" :key="job.id">
                <td><span class="job-id">{{ job.id }}</span></td>
                <td>{{ job.client }}</td>
                <td>{{ job.service }}</td>
                <td>{{ job.date }}</td>
                <td class="amount">${{ job.amount }}</td>
                <td><span class="status-badge" :class="job.status">{{ job.statusLabel }}</span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const showQuickSchedule = ref(false)

const kpis = [
  {
    label: "Today's Jobs",
    value: '6',
    trend: '+2 vs yesterday',
    trendType: 'up',
    bg: 'rgba(33, 150, 243, 0.1)',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="#2196F3" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>'
  },
  {
    label: 'Active Clients',
    value: '234',
    trend: '+12 this month',
    trendType: 'up',
    bg: 'rgba(76, 175, 80, 0.1)',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="#4caf50" stroke-width="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg>'
  },
  {
    label: 'Monthly Revenue',
    value: '$18,200',
    trend: '+8.3% vs last month',
    trendType: 'up',
    bg: 'rgba(26, 35, 126, 0.1)',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="#1a237e" stroke-width="2"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>'
  },
  {
    label: 'Avg Rating',
    value: '4.8',
    trend: '98% satisfaction',
    trendType: 'neutral',
    bg: 'rgba(255, 152, 0, 0.1)',
    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="#ff9800" stroke-width="2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>'
  }
]

const chartData = [
  { month: 'Jul', value: '12.4k', height: 62 },
  { month: 'Aug', value: '14.1k', height: 71 },
  { month: 'Sep', value: '13.6k', height: 68 },
  { month: 'Oct', value: '15.8k', height: 79 },
  { month: 'Nov', value: '16.5k', height: 83 },
  { month: 'Dec', value: '14.9k', height: 75 },
  { month: 'Jan', value: '17.2k', height: 86 },
  { month: 'Feb', value: '16.8k', height: 84 },
  { month: 'Mar', value: '18.2k', height: 91 }
]

const todayJobs = [
  { time: '8:00 AM', client: 'Sarah Mitchell', service: 'Regular - 3BR', status: 'completed', statusLabel: 'Done' },
  { time: '10:30 AM', client: 'James Lee', service: 'Deep Clean - 2BR', status: 'progress', statusLabel: 'In Progress' },
  { time: '1:00 PM', client: 'Maria Garcia', service: 'Regular - Studio', status: 'scheduled', statusLabel: 'Upcoming' },
  { time: '3:00 PM', client: 'Tom Wilson', service: 'Move Out - 1BR', status: 'scheduled', statusLabel: 'Upcoming' },
  { time: '4:30 PM', client: 'Chen Wei', service: 'Office - Suite 200', status: 'scheduled', statusLabel: 'Upcoming' },
  { time: '6:00 PM', client: 'Alex Park', service: 'Regular - 2BR', status: 'scheduled', statusLabel: 'Upcoming' }
]

const jobs = [
  { id: 'PC-2847', client: 'Sarah Mitchell', service: 'Regular Cleaning', date: 'Mar 21, 2026', amount: '149', status: 'completed', statusLabel: 'Completed' },
  { id: 'PC-2846', client: 'David Chen', service: 'Office Cleaning', date: 'Mar 21, 2026', amount: '299', status: 'progress', statusLabel: 'In Progress' },
  { id: 'PC-2845', client: 'Emily Rodriguez', service: 'Move Out', date: 'Mar 20, 2026', amount: '249', status: 'completed', statusLabel: 'Completed' },
  { id: 'PC-2844', client: 'Lisa Park', service: 'Deep Cleaning', date: 'Mar 20, 2026', amount: '199', status: 'completed', statusLabel: 'Completed' },
  { id: 'PC-2843', client: 'James Wilson', service: 'Regular Cleaning', date: 'Mar 19, 2026', amount: '99', status: 'completed', statusLabel: 'Completed' },
  { id: 'PC-2842', client: 'Maria Garcia', service: 'Post-Construction', date: 'Mar 19, 2026', amount: '349', status: 'completed', statusLabel: 'Completed' },
  { id: 'PC-2841', client: 'Tom Brown', service: 'Regular Cleaning', date: 'Mar 18, 2026', amount: '149', status: 'cancelled', statusLabel: 'Cancelled' },
  { id: 'PC-2840', client: 'Anna Kim', service: 'Carpet Cleaning', date: 'Mar 18, 2026', amount: '149', status: 'completed', statusLabel: 'Completed' }
]
</script>

<style scoped>
.admin-page {
  display: flex;
  min-height: 100vh;
  background: var(--bg-light);
}

/* Sidebar */
.admin-sidebar {
  width: 260px;
  background: var(--secondary);
  color: var(--white);
  display: flex;
  flex-direction: column;
  position: fixed;
  top: 0;
  left: 0;
  height: 100vh;
  z-index: 100;
}

.sidebar-logo {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 1.5rem;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.sidebar-logo svg { width: 32px; height: 32px; }

.sidebar-brand {
  font-family: var(--font-heading);
  font-weight: 800;
  font-size: 1rem;
  letter-spacing: 0.08em;
  display: block;
}

.sidebar-sub {
  font-size: 0.7rem;
  color: var(--primary-light);
  letter-spacing: 0.1em;
}

.sidebar-nav {
  flex: 1;
  padding: 1rem 0;
  overflow-y: auto;
}

.sidebar-link {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.75rem 1.5rem;
  font-size: 0.9rem;
  color: rgba(255, 255, 255, 0.6);
  transition: all var(--transition-fast);
}

.sidebar-link:hover { color: var(--white); background: rgba(255, 255, 255, 0.05); }
.sidebar-link.active { color: var(--white); background: rgba(255, 255, 255, 0.1); border-right: 3px solid var(--primary); }
.sidebar-link svg { width: 20px; height: 20px; flex-shrink: 0; }

.sidebar-footer {
  padding: 1rem 0;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

/* Main */
.admin-main {
  flex: 1;
  margin-left: 260px;
  padding: 2rem;
}

.admin-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 2rem;
  flex-wrap: wrap;
  gap: 1rem;
}

.admin-header h1 {
  font-size: 1.75rem;
  margin-bottom: 0.25rem;
}

.admin-header p {
  font-size: 0.9rem;
  color: var(--text-muted);
  margin: 0;
}

.header-actions {
  display: flex;
  gap: 1rem;
  align-items: center;
}

.admin-search {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  background: var(--white);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 0.5rem 1rem;
}

.admin-search svg { width: 18px; height: 18px; color: var(--text-muted); }
.admin-search input { border: none; outline: none; font-family: var(--font-body); font-size: 0.9rem; width: 200px; }

/* KPI */
.kpi-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.kpi-card {
  background: var(--white);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  display: flex;
  align-items: center;
  gap: 1rem;
  box-shadow: var(--shadow-sm);
}

.kpi-icon {
  width: 52px;
  height: 52px;
  border-radius: var(--radius);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  padding: 12px;
}

.kpi-label { display: block; font-size: 0.8rem; color: var(--text-muted); margin-bottom: 0.25rem; }
.kpi-value { display: block; font-family: var(--font-accent); font-size: 1.75rem; font-weight: 700; color: var(--secondary); line-height: 1.2; }
.kpi-trend { font-size: 0.75rem; color: var(--text-muted); }
.kpi-trend.up { color: var(--success); }

/* Grid */
.admin-grid {
  display: grid;
  grid-template-columns: 1.5fr 1fr;
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.admin-card {
  background: var(--white);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  box-shadow: var(--shadow-sm);
}

.admin-card h3 {
  font-size: 1.1rem;
  margin-bottom: 1.5rem;
}

/* Chart */
.chart-container { padding: 0.5rem 0; }

.chart-bars {
  display: flex;
  align-items: flex-end;
  gap: 0.75rem;
  height: 220px;
  padding-bottom: 1.5rem;
}

.chart-bar-group {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 100%;
  justify-content: flex-end;
}

.chart-bar {
  width: 100%;
  max-width: 48px;
  background: linear-gradient(180deg, var(--primary) 0%, var(--primary-light) 100%);
  border-radius: 6px 6px 0 0;
  position: relative;
  transition: height 0.6s ease;
  min-height: 20px;
}

.chart-value {
  position: absolute;
  top: -22px;
  left: 50%;
  transform: translateX(-50%);
  font-family: var(--font-accent);
  font-size: 0.65rem;
  color: var(--text-muted);
  white-space: nowrap;
}

.chart-label {
  font-size: 0.75rem;
  color: var(--text-muted);
  margin-top: 0.5rem;
}

/* Quick form */
.quick-form .form-group { margin-bottom: 1rem; }
.quick-form label { font-size: 0.85rem; }
.quick-form select, .quick-form input { padding: 0.6rem 0.75rem; font-size: 0.85rem; }

/* Today's schedule */
.upcoming-jobs h4 {
  font-size: 0.9rem;
  margin-bottom: 1rem;
  color: var(--text);
}

.job-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.6rem 0;
  border-bottom: 1px solid var(--border);
}

.job-item:last-child { border-bottom: none; }

.job-time {
  font-family: var(--font-accent);
  font-size: 0.75rem;
  color: var(--text-muted);
  min-width: 60px;
}

.job-detail { flex: 1; }
.job-detail strong { display: block; font-size: 0.85rem; color: var(--text); }
.job-detail span { font-size: 0.75rem; color: var(--text-muted); }

.job-status {
  font-size: 0.7rem;
  font-weight: 600;
  padding: 0.2rem 0.6rem;
  border-radius: 50px;
}

.job-status.completed { background: rgba(76, 175, 80, 0.1); color: var(--success); }
.job-status.progress { background: rgba(33, 150, 243, 0.1); color: var(--primary); }
.job-status.scheduled { background: rgba(255, 152, 0, 0.1); color: var(--warning); }

/* Table */
.table-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.table-header h3 { margin: 0; }

.table-filter {
  padding: 0.4rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  font-family: var(--font-body);
  font-size: 0.85rem;
  color: var(--text);
  background: var(--white);
  outline: none;
}

.table-wrapper { overflow-x: auto; }

.admin-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.9rem;
}

.admin-table th {
  text-align: left;
  padding: 0.75rem 1rem;
  font-family: var(--font-heading);
  font-weight: 600;
  font-size: 0.8rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border-bottom: 2px solid var(--border);
}

.admin-table td {
  padding: 0.75rem 1rem;
  border-bottom: 1px solid var(--border);
  color: var(--text);
}

.job-id {
  font-family: var(--font-accent);
  font-size: 0.8rem;
  color: var(--primary);
}

.amount {
  font-family: var(--font-accent);
  font-weight: 700;
}

.status-badge {
  font-size: 0.75rem;
  font-weight: 600;
  padding: 0.25rem 0.75rem;
  border-radius: 50px;
  white-space: nowrap;
}

.status-badge.completed { background: rgba(76, 175, 80, 0.1); color: var(--success); }
.status-badge.progress { background: rgba(33, 150, 243, 0.1); color: var(--primary); }
.status-badge.scheduled { background: rgba(255, 152, 0, 0.1); color: var(--warning); }
.status-badge.cancelled { background: rgba(244, 67, 54, 0.1); color: var(--danger); }

@media (max-width: 768px) {
  .admin-sidebar {
    width: 60px;
    overflow: hidden;
  }
  .sidebar-logo div, .sidebar-link span, .sidebar-brand, .sidebar-sub { display: none; }
  .sidebar-logo { justify-content: center; padding: 1rem; }
  .sidebar-link { justify-content: center; padding: 0.75rem; }
  .admin-main { margin-left: 60px; padding: 1rem; }
  .kpi-grid { grid-template-columns: 1fr 1fr; }
  .admin-grid { grid-template-columns: 1fr; }
  .header-actions { flex-wrap: wrap; }
  .admin-search input { width: 120px; }
}

@media (max-width: 480px) {
  .kpi-grid { grid-template-columns: 1fr; }
}
</style>

// websites/crestview-financial/src/pages/Admin.jsx
import { useState, useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import './Admin.css'

function Admin() {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [animatedKPIs, setAnimatedKPIs] = useState({ clients: 0, pipeline: 0, mortgages: 0, revenue: 0 })
  const chartRef = useRef(null)
  const [chartAnimated, setChartAnimated] = useState(false)

  // Animate KPIs on mount
  useEffect(() => {
    const targets = { clients: 342, pipeline: 12.4, mortgages: 89, revenue: 187 }
    const duration = 1500
    const start = performance.now()

    const animate = (time) => {
      const progress = Math.min((time - start) / duration, 1)
      const eased = 1 - Math.pow(1 - progress, 3)
      setAnimatedKPIs({
        clients: Math.floor(targets.clients * eased),
        pipeline: parseFloat((targets.pipeline * eased).toFixed(1)),
        mortgages: Math.floor(targets.mortgages * eased),
        revenue: Math.floor(targets.revenue * eased)
      })
      if (progress < 1) requestAnimationFrame(animate)
    }
    requestAnimationFrame(animate)
  }, [])

  // Animate chart on scroll
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setChartAnimated(true)
          observer.disconnect()
        }
      },
      { threshold: 0.3 }
    )

    if (chartRef.current) observer.observe(chartRef.current)
    return () => observer.disconnect()
  }, [])

  const kpis = [
    {
      label: 'Active Clients',
      value: animatedKPIs.clients,
      format: (v) => v.toString(),
      change: '+12',
      changeLabel: 'this month',
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4-4v2"/>
          <circle cx="9" cy="7" r="4"/>
          <path d="M23 21v-2a4 4 0 00-3-3.87"/>
          <path d="M16 3.13a4 4 0 010 7.75"/>
        </svg>
      )
    },
    {
      label: 'Pipeline Value',
      value: animatedKPIs.pipeline,
      format: (v) => `$${v}M`,
      change: '+$2.1M',
      changeLabel: 'vs last month',
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <line x1="12" y1="1" x2="12" y2="23"/>
          <path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/>
        </svg>
      )
    },
    {
      label: 'Mortgages Closed',
      value: animatedKPIs.mortgages,
      format: (v) => v.toString(),
      change: '+8',
      changeLabel: 'this quarter',
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/>
          <polyline points="9 22 9 12 15 12 15 22"/>
        </svg>
      )
    },
    {
      label: 'Monthly Revenue',
      value: animatedKPIs.revenue,
      format: (v) => `$${v}K`,
      change: '+15%',
      changeLabel: 'vs last month',
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/>
          <polyline points="17 6 23 6 23 12"/>
        </svg>
      )
    }
  ]

  const pipeline = [
    { id: 'APP-2024-001', client: 'James & Linda Morrison', type: 'Residential Purchase', amount: '$680,000', status: 'Funded', date: '2024-03-15' },
    { id: 'APP-2024-002', client: 'TechVentures LLC', type: 'Commercial Mortgage', amount: '$2,400,000', status: 'Approved', date: '2024-03-12' },
    { id: 'APP-2024-003', client: 'Maria Santos', type: 'Refinance', amount: '$425,000', status: 'Under Review', date: '2024-03-10' },
    { id: 'APP-2024-004', client: 'David Park', type: 'Residential Purchase', amount: '$550,000', status: 'Submitted', date: '2024-03-08' },
    { id: 'APP-2024-005', client: 'Greenfield Realty Group', type: 'Commercial Mortgage', amount: '$3,800,000', status: 'Under Review', date: '2024-03-05' },
    { id: 'APP-2024-006', client: 'Emily & Tom Watson', type: 'Residential Purchase', amount: '$375,000', status: 'Approved', date: '2024-03-01' }
  ]

  const filteredPipeline = pipeline.filter(p =>
    p.client.toLowerCase().includes(searchQuery.toLowerCase()) ||
    p.id.toLowerCase().includes(searchQuery.toLowerCase())
  )

  const statusColors = {
    'Funded': { bg: 'rgba(39, 174, 96, 0.1)', color: '#27ae60' },
    'Approved': { bg: 'rgba(52, 152, 219, 0.1)', color: '#3498db' },
    'Under Review': { bg: 'rgba(243, 156, 18, 0.1)', color: '#f39c12' },
    'Submitted': { bg: 'rgba(149, 165, 166, 0.1)', color: '#95a5a6' }
  }

  // Chart data - 6 months of performance
  const chartData = [
    { month: 'Oct', value: 142 },
    { month: 'Nov', value: 158 },
    { month: 'Dec', value: 135 },
    { month: 'Jan', value: 168 },
    { month: 'Feb', value: 175 },
    { month: 'Mar', value: 187 }
  ]

  const chartMax = Math.max(...chartData.map(d => d.value))
  const chartMin = Math.min(...chartData.map(d => d.value)) - 20
  const chartHeight = 200
  const chartWidth = 500
  const padding = 40

  const getY = (value) => {
    return chartHeight - padding - ((value - chartMin) / (chartMax - chartMin)) * (chartHeight - 2 * padding)
  }

  const getX = (index) => {
    return padding + (index / (chartData.length - 1)) * (chartWidth - 2 * padding)
  }

  const linePath = chartData.map((d, i) => {
    const x = getX(i)
    const y = getY(d.value)
    return `${i === 0 ? 'M' : 'L'} ${x} ${y}`
  }).join(' ')

  const areaPath = linePath + ` L ${getX(chartData.length - 1)} ${chartHeight - padding} L ${getX(0)} ${chartHeight - padding} Z`

  return (
    <div className="admin-page">
      {/* Sidebar */}
      <aside className={`admin-sidebar ${sidebarOpen ? 'open' : ''}`}>
        <div className="admin-sidebar-header">
          <Link to="/" className="admin-sidebar-logo">
            <svg width="32" height="32" viewBox="0 0 40 40" fill="none">
              <path d="M20 4L6 28H14L20 16L26 28H34L20 4Z" fill="var(--white)" />
              <path d="M20 16L14 28H26L20 16Z" fill="var(--gold)" opacity="0.8" />
            </svg>
            <span>CRESTVIEW</span>
          </Link>
        </div>

        <nav className="admin-sidebar-nav">
          <a href="#" className="admin-nav-item active">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="3" y="3" width="7" height="7"/>
              <rect x="14" y="3" width="7" height="7"/>
              <rect x="3" y="14" width="7" height="7"/>
              <rect x="14" y="14" width="7" height="7"/>
            </svg>
            <span>Dashboard</span>
          </a>
          <a href="#" className="admin-nav-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4-4v2"/>
              <circle cx="9" cy="7" r="4"/>
              <path d="M23 21v-2a4 4 0 00-3-3.87"/>
              <path d="M16 3.13a4 4 0 010 7.75"/>
            </svg>
            <span>Clients</span>
          </a>
          <a href="#" className="admin-nav-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
              <polyline points="14 2 14 8 20 8"/>
            </svg>
            <span>Applications</span>
          </a>
          <a href="#" className="admin-nav-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/>
              <polyline points="17 6 23 6 23 12"/>
            </svg>
            <span>Analytics</span>
          </a>
          <a href="#" className="admin-nav-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="3"/>
              <path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-2 2 2 2 0 01-2-2v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83 0 2 2 0 010-2.83l.06-.06a1.65 1.65 0 00.33-1.82 1.65 1.65 0 00-1.51-1H3a2 2 0 01-2-2 2 2 0 012-2h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06a1.65 1.65 0 001.82.33H9a1.65 1.65 0 001-1.51V3a2 2 0 012-2 2 2 0 012 2v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06a1.65 1.65 0 00-.33 1.82V9a1.65 1.65 0 001.51 1H21a2 2 0 012 2 2 2 0 01-2 2h-.09a1.65 1.65 0 00-1.51 1z"/>
            </svg>
            <span>Settings</span>
          </a>
        </nav>

        <div className="admin-sidebar-footer">
          <Link to="/" className="admin-nav-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M9 21H5a2 2 0 01-2-2V5a2 2 0 012-2h4"/>
              <polyline points="16 17 21 12 16 7"/>
              <line x1="21" y1="12" x2="9" y2="12"/>
            </svg>
            <span>Sign Out</span>
          </Link>
        </div>
      </aside>

      {/* Mobile sidebar overlay */}
      {sidebarOpen && <div className="admin-overlay" onClick={() => setSidebarOpen(false)} />}

      {/* Main Content */}
      <main className="admin-main">
        {/* Top Bar */}
        <header className="admin-topbar">
          <button className="admin-menu-btn" onClick={() => setSidebarOpen(!sidebarOpen)}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="3" y1="6" x2="21" y2="6"/>
              <line x1="3" y1="12" x2="21" y2="12"/>
              <line x1="3" y1="18" x2="21" y2="18"/>
            </svg>
          </button>
          <h1 className="admin-page-title">Dashboard</h1>
          <div className="admin-topbar-right">
            <div className="admin-search">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="11" cy="11" r="8"/>
                <line x1="21" y1="21" x2="16.65" y2="16.65"/>
              </svg>
              <input
                type="text"
                placeholder="Search clients..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="admin-search-input"
              />
            </div>
            <div className="admin-user">
              <div className="admin-user-avatar">JB</div>
              <span className="admin-user-name">J. Blake</span>
            </div>
          </div>
        </header>

        {/* KPI Cards */}
        <div className="admin-kpis">
          {kpis.map((kpi, i) => (
            <div key={i} className="admin-kpi-card" style={{ animationDelay: `${i * 100}ms` }}>
              <div className="admin-kpi-header">
                <div className="admin-kpi-icon">{kpi.icon}</div>
                <div className="admin-kpi-change">
                  <span className="admin-kpi-change-value">{kpi.change}</span>
                  <span className="admin-kpi-change-label">{kpi.changeLabel}</span>
                </div>
              </div>
              <div className="admin-kpi-value">{kpi.format(kpi.value)}</div>
              <div className="admin-kpi-label">{kpi.label}</div>
            </div>
          ))}
        </div>

        {/* Chart and Pipeline */}
        <div className="admin-content-grid">
          {/* Chart */}
          <div className="admin-chart-card" ref={chartRef}>
            <div className="admin-card-header">
              <h3>Monthly Revenue</h3>
              <span className="admin-card-badge">Last 6 months</span>
            </div>
            <div className="admin-chart-wrap">
              <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} className="admin-chart-svg">
                {/* Grid lines */}
                {[0, 1, 2, 3, 4].map(i => {
                  const val = chartMin + ((chartMax - chartMin) / 4) * i
                  const y = getY(val)
                  return (
                    <g key={i}>
                      <line x1={padding} y1={y} x2={chartWidth - padding} y2={y} stroke="var(--medium-gray)" strokeWidth="1" strokeDasharray="4 4" />
                      <text x={padding - 8} y={y + 4} textAnchor="end" fill="var(--text-gray)" fontSize="10" fontFamily="var(--font-mono)">
                        ${Math.round(val)}K
                      </text>
                    </g>
                  )
                })}

                {/* X-axis labels */}
                {chartData.map((d, i) => (
                  <text key={i} x={getX(i)} y={chartHeight - 10} textAnchor="middle" fill="var(--text-gray)" fontSize="11" fontFamily="var(--font-body)">
                    {d.month}
                  </text>
                ))}

                {/* Area fill */}
                <path
                  d={areaPath}
                  fill="url(#chartGradient)"
                  opacity={chartAnimated ? 0.15 : 0}
                  style={{ transition: 'opacity 0.8s ease' }}
                />

                {/* Line */}
                <path
                  d={linePath}
                  fill="none"
                  stroke="var(--gold)"
                  strokeWidth="3"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeDasharray={chartAnimated ? 'none' : '1000'}
                  strokeDashoffset={chartAnimated ? 0 : 1000}
                  style={{ transition: 'stroke-dashoffset 1.2s ease' }}
                />

                {/* Data points */}
                {chartData.map((d, i) => (
                  <g key={i}>
                    <circle
                      cx={getX(i)}
                      cy={getY(d.value)}
                      r={chartAnimated ? 5 : 0}
                      fill="var(--navy)"
                      stroke="var(--gold)"
                      strokeWidth="2.5"
                      style={{ transition: `r 0.3s ease ${i * 100 + 600}ms` }}
                    />
                    <text
                      x={getX(i)}
                      y={getY(d.value) - 14}
                      textAnchor="middle"
                      fill="var(--navy)"
                      fontSize="11"
                      fontWeight="700"
                      fontFamily="var(--font-mono)"
                      opacity={chartAnimated ? 1 : 0}
                      style={{ transition: `opacity 0.3s ease ${i * 100 + 800}ms` }}
                    >
                      ${d.value}K
                    </text>
                  </g>
                ))}

                <defs>
                  <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="var(--gold)" />
                    <stop offset="100%" stopColor="var(--gold)" stopOpacity="0" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
          </div>

          {/* Pipeline Table */}
          <div className="admin-pipeline-card">
            <div className="admin-card-header">
              <h3>Application Pipeline</h3>
              <span className="admin-card-badge">{pipeline.length} active</span>
            </div>
            <div className="admin-table-wrap">
              <table className="admin-table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Client</th>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredPipeline.map((item, i) => (
                    <tr key={i}>
                      <td className="admin-table-id">{item.id}</td>
                      <td className="admin-table-client">{item.client}</td>
                      <td>{item.type}</td>
                      <td className="admin-table-amount">{item.amount}</td>
                      <td>
                        <span
                          className="admin-status-badge"
                          style={{
                            background: statusColors[item.status]?.bg,
                            color: statusColors[item.status]?.color
                          }}
                        >
                          {item.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                  {filteredPipeline.length === 0 && (
                    <tr>
                      <td colSpan="5" style={{ textAlign: 'center', padding: '32px', color: 'var(--text-gray)' }}>
                        No matching applications found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Admin
