// websites/northgate-law/src/components/ScrollReveal.jsx
import { useEffect, useRef } from 'react'

export default function ScrollReveal({ children, className = '', delay = 0, direction = 'up' }) {
  const ref = useRef(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setTimeout(() => {
            el.classList.add('visible')
          }, delay)
          observer.unobserve(el)
        }
      },
      { threshold: 0.15 }
    )

    observer.observe(el)
    return () => observer.disconnect()
  }, [delay])

  const dirClass = direction === 'left' ? 'reveal-left' : direction === 'right' ? 'reveal-right' : 'reveal'

  return (
    <div ref={ref} className={`${dirClass} ${className}`}>
      {children}
    </div>
  )
}

// websites/apex-auto-detail/src/components/ScrollReveal.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const props = defineProps({
  delay: { type: Number, default: 0 },
  direction: { type: String, default: 'up' }
})

const el = ref(null)
const isVisible = ref(false)
let observer = null

onMounted(() => {
  observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting) {
        setTimeout(() => {
          isVisible.value = true
        }, props.delay)
        observer.unobserve(entry.target)
      }
    },
    { threshold: 0.1 }
  )
  if (el.value) {
    observer.observe(el.value)
  }
})

onUnmounted(() => {
  if (observer) observer.disconnect()
})

const className = props.direction === 'left'
  ? 'reveal-left'
  : props.direction === 'right'
    ? 'reveal-right'
    : 'reveal'
</script>

<template>
  <div ref="el" :class="[className, { visible: isVisible }]">
    <slot />
  </div>
</template>
